workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
    - if: $CI_COMMIT_BRANCH

stages:
  - fetch
  - build-image
  - push

variables:
  GIT_STRATEGY: none
  REPO_URL: "https://github.aai.aero/Solarman/test5555.git"
  DOCKER_IMAGE_NAME: "my-app"
  DOCKER_TLS_CERTDIR: "/certs"

fetch-code:
  stage: fetch
  image: alpine/git:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
  script:
    - echo "Fetching GitHub repo $REPO_URL at commit $COMMIT_SHA on branch $BRANCH"
    - git clone $REPO_URL .
    - git checkout $COMMIT_SHA
    - ls -la
    - echo "Files fetched successfully"
  artifacts:
    paths:
      - .
    expire_in: 1 hour
    when: always

build-image:
  stage: build-image
  image: docker:24.0
  services:
    - name: docker:24.0-dind
      alias: docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "Building image for commit $COMMIT_SHA"
    - docker info
  script:
    - docker build --network=host -t $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:temp .
    - docker tag $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:temp $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:$COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:temp $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:latest
    - docker rmi $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:temp
    - echo "Image built: $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:$COMMIT_SHA"
    - docker images
  needs:
    - fetch-code

push-image:
  stage: push
  image: docker:24.0
  services:
    - name: docker:24.0-dind
      alias: docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "Logged in to registry: $CI_REGISTRY"
  script:
    - docker push $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:$COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:latest
    - echo "Pushed image: $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:$COMMIT_SHA"
  needs:
    - build-image
  when: on_success